###
POST http://localhost:3000/api/users HTTP/1.1
content-Type: application/json

{
    "name": "Loquillo",
    "age": 33,
    "email": "fedeloco@gmail.com" 
}

###
POST http://localhost:3000/api/users HTTP/1.1
content-Type: application/json

{
    "name": "Murciego",
    "age": 13,
    "email": "jijiojoj@gmail.com" 
}

###
GET http://localhost:3000/api/users/61876575e0fc5437cc66e3d4 HTTP/1.1

###
DELETE http://localhost:3000/api/users/6185bf108f7b0f6ee9639eac HTTP/1.1

###
PUT http://localhost:3000/api/users/6185bf108f7b0f6ee9639eac HTTP/1.1
Content-Type: application/json

{
    "name": "Cristian",
    "age": 28,
    "email": "cdestradab@gmail.com"
}